services:
  arcainer:
    container_name: arcainer
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - arcainer_storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock

      # 1- NO RELATIVE PATH (./stacks:./stacks ❌) (/opt/stacks:/opt/stacks ✅)
      # 2- LEFT AND RIGHT PATH NEED TO BE THE SAME (/app/composes:/app/stacks ❌) (/app/stacks:/app/stacks ✅)
      - /opt/stacks:/opt/stacks
    environment:
      # STACKS_PATH NEED TO BE THE SAME AS ABOVE IF YOU CHANGE THIS CHANGE THE ABOVE TOO
      - STACKS_PATH=/opt/stacks

volumes:
    arcainer_storage:
      name: arcainer_storage