services:
  arcainer:
    container_name: arcainer
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock