services:
  arcainer:
    container_name: arcainer
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - arcainer_storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock

      - ./stacks:/opt/stacks
    environment:
      # STACKS_PATH NEED TO BE THE SAME AS ABOVE IF YOU CHANGE THIS CHANGE THE ABOVE TOO
      - STACKS_PATH=/opt/stacks

volumes:
    arcainer_storage:
      name: arcainer_storage